name: fl_paging
description: A new Flutter package support paginating for Listview, Gridview and NestedScrollView
version: 2.2.0
homepage: https://github.com/dangngocduc/flutter_paging
repository: https://github.com/dangngocduc/flutter_paging
issue_tracker: https://github.com/dangngocduc/flutter_paging/issues
documentation: https://github.com/dangngocduc/flutter_paging

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
  freezed_annotation: ^2.2.0
  tuple: ^2.0.0
  async: ^2.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.0
  freezed: ^2.2.1
flutter:
